# cd /mnt/d/Users/timakov/PhpstormProjects/game2

# docker-compose  --project-directory /mnt/d/Users/timakov/PhpstormProjects/game2 up -d
version: '3'
services:
  game2main:
    build:
        context: .docker
        dockerfile: Dockerfile
    image: game2main
    ports:
        - '80:80'
    volumes:
        - '.:/var/www/html'
    depends_on:
        - db
    networks:
      - game2

  db:
    container_name:  pgdb
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: game2
    ports:
      - "5433:5432"
    networks:
      - game2

networks:
  game2:
    external: true
